function [ ] = segment_gui( images, prevGui )
    if nargin < 2
      prevGui = -1;
    end
    
    nameWindow = '';
    if isstruct(prevGui)
        nameWindow = get(prevGui.f,'name');
    end
    % Page 2 : segmentation
    S.f = figure('visible','off',...
            'Units','normalized',...
            'outerposition',[0 0 1 1],...
              'menubar','none',...
              'resize','on',...
              'numbertitle','off',...
              'name',nameWindow);
    
    S.hPanel = uipanel('Position',[0.05 0.15 0.9 0.6], 'Parent',S.f,'BackgroundColor',[1 1 1]);      
    
    S.images = images;
    S.hImages = [];
    ncol = ceil(length(images)/2);
    nrow = 2;
    for i = 1:size(images,2)
      image = S.images(i).im;
      S.hImages(i) = axes('Parent',S.hPanel, ...
        'Position',[mod(i-1,ncol)/ncol 1-(floor((i-1)/ncol)+1-0.03)/nrow 1/ncol 1/nrow-0.06]);
      set(S.hImages(i),'Visible','on');
      imagesc(image);axis image;colormap gray
      set(S.hImages(i),'xtick',[]);
      set(S.hImages(i),'ytick',[]);
    end
    
    uicontrol(...
    'Parent',S.f,...
    'Units','normalized',...
    'CData',[],...
    'Position',[0.4 0.96 0.2 0.02],...
    'String','Number of regions',...
    'Style','text',...
    'UserData',[],...
    'Tag','text10',...
    'BackgroundColor',get(S.f,'Color'));

    heNumRegions = uicontrol(...
    'Parent',S.f,...
    'Units','normalized',...
    'CData',[],...
    'Position',[0.4 0.92 0.2 0.04],...
    'Style','edit',...
    'String','3',...
    'UserData',[],...
    'Tag','edit19');


    segment_btn = uicontrol('style','push',...
                 'units','normalized',...
                 'position',[0.05 0.8 0.9 0.10],...
                 'backgroundcolor','w',...
                 'HorizontalAlign','left',...
                 'string','Segment',...
                 'fontsize',11,'fontweight','bold',...
                 'callback',{@segment_btn_call});

    prev_btn = uicontrol('style','push',...
                 'units','normalized',...
                 'position',[0.15 0.05 0.2 0.05],...
                 'HorizontalAlign','left',...
                 'string','Previous (loading)',...
                 'fontsize',11,...
                 'callback',{@prev_btn_call,S,prevGui});
             
    next_btn = uicontrol('style','push',...
                 'units','normalized',...
                 'position',[0.75 0.05 0.2 0.05],...
                 'HorizontalAlign','left',...
                 'string','Next (registration)',...
                 'fontsize',11,...
                 'callback',{@next_btn_call});
             
    set(S.f,'Visible','on')
    
    function [] = segment_btn_call(varargin)
        watchon;drawnow;
        for i = 1:length(S.images)
            nRegions = str2double(get(heNumRegions,'String'));
            [~,S.images(i).mask] = segment_cortex(S.images(i).im,nRegions);
            S.hImages(i) = axes('Parent',S.hPanel, ...
            'Position',[mod(i-1,ncol)/ncol 1-(floor((i-1)/ncol)+1-0.03)/nrow 1/ncol 1/nrow-0.06]);
            set(S.hImages(i),'Visible','on');
            imagesc(S.images(i).mask.*S.images(i).im);axis image;colormap gray
            set(S.hImages(i),'xtick',[]);
            set(S.hImages(i),'ytick',[]);
        end
        assignin('base','images',S.images);
        watchoff;drawnow;
    end

    function [] = prev_btn_call(varargin)
        %set(varargin{3}.f,'visible','off');
        delete(varargin{3}.f); % Going back to previous GUI deletes the current GUI
        set(varargin{4}.f,'visible','on');
    end

    function [] = next_btn_call(varargin)
        set(S.f,'visible','off');
        register_gui(S.images,S); % Call next page GUI
    end

end

